### ISSUE TITLE
Badges should be aligned with Title

### ISSUE THREAD

**Issue by pawarashish564** [othneildrew/Best-README-Template#11]
It looks kinda absurd badges are aligned left and the title goes under it.

**Comment by deep5050** [comment]
Agree @pawarashish564 !!

**Comment by pawarashish564** [comment]
See my PR @deep5050

**Comment by deep5050** [comment]
> See my PR @deep5050

Already using it 💙

**Comment by othneildrew** [comment]
Thanks for the feedback! I'll get right on it along with the other changes suggested.
