### ISSUE TITLE
name attribute removed in HTML 5 for href tag

### ISSUE THREAD

**Issue by dan-m0** [othneildrew/Best-README-Template#121]
## Describe the bug
The back to top link does not work correctly.

### Steps to reproduce
1. Copy/paste template into a markdown file
2. Click any back to top link

### Expected behavior
Jump back to the top due to this line

```md
<a name="readme-top"></a>
```

### Environment
 - OS: MacOS Sanoma - Version 14.4.1 (23E224)
 - Macbook - Apple M1 Pro

### Additional context
I don't have time now, but I will fork, fix, and PR later today.

The fix, if anyone can do it sooner, is to change the line to

```md
<a id="readme-top"></a>
```

### Why?

Usage of the name attribute in this way is depreciated, and was removed from HTML 5 [wikipedia](https://en.wikipedia.org/wiki/HTML5)

See [here](https://www.w3schools.com/tags/att_name.asp), [here](https://www.w3schools.com/tags/att_id.asp) and [here](https://legacy.forums.gravityhelp.com/topic/name-attribute-a-anchor-tag-is-obsolete-in-html5#post-71919) to verify

**Comment by Abdelhay1212** [comment]
Hello nyxtryx I’ve created a pull request to fix the "Back to top" link by replacing the deprecated `name` attribute with the `id` attribute. This should resolve the problem across all modern browsers.

Feel free to review the PR [#122] and provide any feedback.
