### ISSUE TITLE
Adding repobeat and contrib section

### ISSUE THREAD

**Issue by Sbrjt** [othneildrew/Best-README-Template#127]
I saw these two awesome templates on a repo, that you might consider adding in the readme.

https://repobeats.axiom.co/

https://contrib.rocks/

## Repobeats:
Shows repo insights

![](https://repobeats.axiom.co/api/embed/324efe7f02eac0ea57d264c986651a346e86caf9.svg "Repobeats analytics image")

## contrib.rocks
Generates an image of contributors

<a href="https://github.com/othneildrew/Best-README-Template/graphs/contributors">
  <img src="https://contrib.rocks/image?repo=othneildrew/Best-README-Template" />
</a

**Comment by Sbrjt** [comment]
I can create a PR, if you like.

**Comment by othneildrew** [comment]
@Sbrjt This looks great. Can you create a PR that adds the contrib.rocks with image of contributors at the bottom. I think the stats are a little too much for most projects.

**Comment by Sbrjt** [comment]
I think the repobeats stats look pretty cool. Some big projects like this [one](https://github.com/DevToys-app/DevToys?tab=readme-ov-file#special-thanks) do use it.

**Comment by othneildrew** [comment]
> I think the repobeats stats look pretty cool. Some big projects like this [one](https://github.com/DevToys-app/DevToys?tab=readme-ov-file#special-thanks) do use it.

I have a tool I'm working on that will bring further customization to the readme, similar to the project you linked; I will keep that in mind for this new tool.

Thanks for the PR
https://github.com/othneildrew/Best-README-Template/pull/129

Closing this issue since it's merged.
