### ISSUE TITLE
Convert this project in "github template"

### ISSUE THREAD

**Issue by davorpa** [othneildrew/Best-README-Template#14]
Hi

It will be very usefull if in repository settings, setup the project as Template.

Therefore any body can know that its a truth template when searching in github.

Thanks in advance

**Comment by PauloHCardosoN** [comment]
Ok, I'm sorry, I didn't know it got in the way.

**Comment by davorpa** [comment]
It's easy.

Follow this guide

https://docs.github.com/es/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/creating-a-template-repository

**Comment by othneildrew** [comment]
Thanks for the feedback! I'll get right on it along with the other changes suggested.
