### ISSUE TITLE
Feedback Request on Recent Changes

### ISSUE THREAD

**Issue by othneildrew** [othneildrew/Best-README-Template#19]
Hi all,

I've made some recent changes to add a collapsible Table of Contents section. I try my best to stick with pure markdown, but this wasn't possible and uses HTML which complicates the process of updating and maintaining your readme overtime. Also, the referenced-styled markdown links have been a little confusing for some.

Please let me know what your thoughts are so I can make the appropriate changes. Ideally, I want the process to be as simple as possible.

**Comment by shadycuz** [comment]
I didn't notice it was collapsible, probably because that's very uncommon in a GitHub readme and because it starts expanded. If it started collapsed it would probably be more intuitive to click it to reveal the contents? 

The template overall is fantastic. Have you used cookie-cutter? That might also make this template easier to setup but would probably add more technical debt for you.

**Comment by othneildrew** [comment]
@shadycuz Thanks for the feedback! I'll change the TOC to start collapsed. As for the cookie-cutter, can you should me a link to what you're referring to? I'm only finding actual cookie-cutters when I search for it. Haha :D

**Comment by shadycuz** [comment]
@othneildrew haha oops, https://github.com/cookiecutter/cookiecutter

It's usually used to create an entire repo in a certain format but I don't see why you couldn't use it for only the readme. 

If you do decide to switch to it, you could use it to generate your blank_readme for non-cookie cutter users.

**Comment by shadycuz** [comment]
Just noticed cookie-cutter readme didn't really explain how it works very well. The gist is similar to your blank_readme. You will declare some variables in your cookie-cutter template. A user will run the cookie-cutter command and then will be prompted to answer those questions. Once done it will generate thole readme file.

**Comment by shadycuz** [comment]
Example template https://github.com/pytest-dev/cookiecutter-pytest-plugin

**Comment by othneildrew** [comment]
Thanks! I see what you mean now. I actually have writing a simple command line script in nodejs as part of the next updates I do so I think that is very similar. I'll read a little more into it and see what works best. I also thought about doing a chrome browser plugin as well, but that is assuming that people will want to use it and that most people use chrome so not entirely set on which direction I'll take just yet. This helps a lot though!

**Comment by linkwoman** [comment]
I like the table of contents, and the consistency with which I'll be able to generate README's with this. thank you for developing and sharing.  What do you think about adding a small "back to toc" at each section?

**Comment by othneildrew** [comment]
Consider it done

> I like the table of contents, and the consistency with which I'll be able to generate README's with this. thank you for developing and sharing. What do you think about adding a small "back to toc" at each section?

Thanks for the feedback. Consider it done! I like the idea of a back to top and will get that added.

**Comment by Alextros00** [comment]
Love this page! Great README

**Comment by othneildrew** [comment]
I'll soon be publishing a very cool update for you guys. You're pull requests and feedback is definitely being taking into consideration so thank you for all the suggestions!
