### ISSUE TITLE
[product-screenshot] on empty template

### ISSUE THREAD

**Issue by lucasliano** [othneildrew/Best-README-Template#25]
Hey, first of all thank you for publishing this! Awesome work :D 

I realized that the "[product-screenshot]: images/screenshot.png" is missing on the empty template, so i wanted to let you know in case you could add it.

Hope you're doing ok, 

Cheers.

**Comment by lucasliano** [comment]
Im also having trouble with tags at the top.. any idea why? The links are working fine.

![Screenshot_20210103_211253](https://user-images.githubusercontent.com/49002137/103492306-b945db00-4e08-11eb-92eb-d9eba7b51ea4.png)

**Comment by othneildrew** [comment]
Will add this. Thanks. And @lucasliano, in the past I've had issues with it on private repos - that might be part, but I'm not 100% sure; have to do a little more research.
