### ISSUE TITLE
Do you need license notice?

### ISSUE THREAD

**Issue by mauro-balades** [othneildrew/Best-README-Template#52]
I was wondering If I use this template. Should I give LICENSE notice to this repo?

**Comment by othneildrew** [comment]
Hi there! Thanks for using this in your project! No license notice is required and you may use this any way you like.

**If you would like to give credit to the template. Place a link back to it in the acknowledgment section of README.**
`- [Best-README-Template](https://github.com/othneildrew/Best-README-Template)`

**Comment by neural-loop** [comment]
Hi, I found this. I might suggest removing the MIT license for a public domain license, as I would like to use this and from this it seems you do not intend to apply the terms of MIT license (which would technically be required in attribution)
