### ISSUE TITLE
add permission

### ISSUE THREAD

**Issue by Avicool20** [othneildrew/Best-README-Template#79]
Hello, Maybe I added the authorization wrongly, but how exactly do I need to enter the server.cfg, which is correct?
No matter what I do, I get this back.
![Screenshot_3](https://user-images.githubusercontent.com/117643795/200293701-9c24fccd-3e25-40cd-ba2b-bd73fe357431.png)
Thx Help! <3

**Comment by othneildrew** [comment]
Unrelated to this project. Please make sure you are asking for help in the correct place.
