### ISSUE TITLE
top section doesnt display for me 

### ISSUE THREAD

**Issue by autumn-skylight** [othneildrew/Best-README-Template#96]
when i ported your amazing template and made my changes the top section doesnt display for me however its display fine when i'm viewing yours, i'm not sure if i'm doing anything wrong (included screenshots and my readme.md file code) [
![Screenshot 2023-06-13 at 20-51-24 othneildrew_Best-README-Template An awesome README template to jumpstart your projects!](https://github.com/othneildrew/Best-README-Template/assets/64833265/affaccd7-b1c5-4e43-8686-54961c57b8c1)
![Screenshot 2023-06-13 at 20-51-03 autumn-skylight_codescape-app all in one app for developers made in electron 20 3 0 (first time using something other then plain html and scss_css](https://github.com/othneildrew/Best-README-Template/assets/64833265/f95c0d57-25bf-4d3e-b603-4181ff6e1872)
![Code_zN7S2RwBY4](https://github.com/othneildrew/Best-README-Template/assets/64833265/3da39d9a-cb3c-4676-a7a8-bfde637d5f13)

**Comment by tyriis** [comment]
@autumn-skylight looks like you are missing the links in the footer section of the markdown when I look at the repository you mentioned in the ticket.
