### ISSUE TITLE
Configuring Redelivery in MassTransit for Individual Service Queues

### ISSUE THREAD

**Issue by ghost** [othneildrew/Best-README-Template#98]
I've been working with MassTransit and have encountered an issue that I'm unable to resolve myself.

In my system, I have multiple services running on a single virtual host. For various reasons, I want to ensure that the redelivery function is handled on separate queues for each service. In particular, I'm aiming to have a distinct Hangfire database for each one.

Could you provide me with guidance on how I can configure the redelivery such that each service can use its own separate queue?

I haven't been able to find clear answers on this in the documentation or through online searching, so any help would be appreciated.

Thanks in advance

**Comment by tyriis** [comment]
@dddcop is this related to the README template?

**Comment by dddcop** [comment]
I do not think so. I was based on the documentation -> https://masstransit.io/documentation/configuration/scheduling

**Comment by tyriis** [comment]
I suggest to create your ticket in the mastransit github repo: https://github.com/MassTransit/MassTransit

**Comment by dddcop** [comment]
Sorry Thank you for your help.
